{
    'name': 'Power Fab Office',
    'version': '17.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'End-to-End Fabrication Management System',
    'description': '''
        Complete fabrication management from project creation, estimation, 
        approval, sales order generation to fabrication execution.
    ''',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': ['base', 'mail', 'sale', 'sale_management', 'project', 'stock', 'uom', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/fab_security.xml',
        'data/sequence_data.xml',
        'data/material_data.xml',
        'data/uom_data.xml',
        'data/stage_data.xml',
        'views/fab_project_views.xml',
        'views/fab_estimation_views.xml',
        'views/fab_order_views.xml',
        'views/fab_material_views.xml',
        'views/fab_team_views.xml',
        'views/res_partner_views.xml',
        'views/menu_views.xml',
        'wizards/fab_estimation_approval_views.xml',
        'wizards/fab_order_cancel_views.xml',
        'wizards/fab_import_bom_wizard_views.xml',
        'reports/fab_estimation_report.xml',
        'reports/fab_order_report.xml',
    ],
    'demo': [
        'demo/fab_material_demo.xml',
        'demo/fab_team_demo.xml',
        'demo/fab_project_demo.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}